import Logo from "@/components/Logo";
import "./globals.css";
import { Space_Mono } from "next/font/google";

const spaceMono = Space_Mono({ subsets: ["latin"], weight: ["700"] });

export const metadata = {
  title: "FrontendMentor Challengue",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-grayish-cyan-light text-[24px] ${spaceMono.className}`}
      >
        <div className="min-h-screen flex flex-col justify-center items-center">
          <span className="mb-10 mt-10 md:mt-0">
            <Logo />
          </span>
          {children}
        </div>
      </body>
    </html>
  );
}
